### ISSUE TITLE
Uncaught Error: Class 'ZipArchive' not found?

### ISSUE THREAD

**Issue by emeraldjava** [MilesChou/composer-action#5]
Hi @MilesChou,

I've been using the 'MilesChou/composer-action' successfully this year and was able to [generate a zip file from by github build](https://github.com/emeraldjava/bhaa-wordpress-plugin/blob/master/.github/workflows/build.yml).

Recently I pushed an update and the build failed with this error claiming that the the ZipArchive was not present.

`    ReleaseBuilder: bhaa-wordpress-plugin.zip 
    > BHAA\utils\ReleaseBuilder::createZip
    Fatal error: Uncaught Error: Class 'ZipArchive' not found in /github/workspace/src/utils/ReleaseBuilder.php:18
    Stack trace:`

From investigate it suggests that the php library for zip is not installed, but i believe it is. I appreciate that the composer-action image is not at issue but might there be a combination of changes to the github ubuntu:latest version which might have caused this issue to start?
Kind Regards,
emeraldjava

**Comment by MilesChou** [comment]
Hi @emeraldjava,

I use unzip command for extract zip file which composer downloaded. Composer Action image just do Composer commands.

I suggest build custom image for using zip ext.

```dockerfile
FROM mileschou/composer:7.4

# or GitHub Container Registry
# FROM ghcr.io/mileschou/composer:7.4

RUN set -xe && \
    apk add --no-cache \
        libzip \
    && \
    apk add --no-cache --virtual .build-deps \
        libzip-dev \
        zlib-dev \
    && \
    docker-php-ext-install -j "$(getconf _NPROCESSORS_ONLN)" \
        zip \
    && \
    apk del --no-cache .build-deps \
    && \
    php -m
```

**Comment by emeraldjava** [comment]
Thanks for the reply. I understand the image only needs unzip to extract the composer download, but zip was part of the original image and isn't any longer. I'll investigate creating a new docker image for my github-action. I suspect switching to something like https://github.com/marketplace/actions/setup-php-action will be an easier path.
