### ISSUE TITLE
Documentation: Composer version - switch version with "major" release. 

### ISSUE THREAD

**Issue by Triloworld** [MilesChou/composer-action#7]
Pleas add note to readme, that Composer upgrade is aligned with "MAJOR" release of this action as this can lead to break CI/CD without notice.

Can I use environment variable to switch version? Is this documented? If not, I propose new feature in separate issue.

Thanks for great work :)

**Comment by MilesChou** [comment]
I will update readme doc this week, and try using environment variable to switch version.

**Comment by MilesChou** [comment]
I decide to add new tag for change to old version.

https://github.com/MilesChou/composer-action#supported-tags-and-respective-dockerfile-links
